// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Login_Api.Models;

namespace Login_Api.Data
{
    public partial class TuyensinhContext : DbContext
    {
        public TuyensinhContext()
        {
        }

        public TuyensinhContext(DbContextOptions<TuyensinhContext> options)
            : base(options)
        {
        }

        public virtual DbSet<DangNhap> DangNhaps { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<DangNhap>(entity =>
            {
                entity.HasKey(e => e.LoginId);

                entity.ToTable("DangNhap");

                entity.HasIndex(e => e.LoginId, "UQ__DangNhap__4DDA28192B3845B8")
                    .IsUnique();

                entity.Property(e => e.LoginId).ValueGeneratedNever();

                entity.Property(e => e.Matkhau)
                    .IsRequired()
                    .HasMaxLength(36);

                entity.Property(e => e.UserName)
                    .IsRequired()
                    .HasMaxLength(36);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}