// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Login_Api.Models
{
    public partial class DangNhap
    {
        public int LoginId { get; set; }
        public string UserName { get; set; }
        public string Matkhau { get; set; }
    }
}